package constant

const (
	Token               = "token"
	BaseUrl             = "base-url"
	BaseUrlDefault      = "https://gitlab.com/api/v4"
	Id                  = "id"
	JobIdRange          = "job-id-range"
	IIdRange            = "iid-range"
	Repository          = "repository"
	TagName             = "tag-name"
	JobId               = "job-id"
	ArtifactsName       = "artifacts-name"
	Sort                = "sort"
	SortDefault         = "desc"
	Page                = "page"
	PerPage             = "per-page"
	PrintJson           = "print-json"
	PrintJsonDefault    = false
	PrintTime           = "print-time"
	PrintTimeDefault    = false
	Scope               = "scope"
	IssueId             = "issue-id"
	IssueIdRange        = "issue-id-range"
	Recursion           = "recursion"
	Owned               = "owned"
	NamespaceSource     = "namespace-source"
	NamespaceTarget     = "namespace-target"
	ExportFolder        = "export-folder"
	SkipProjectPath     = "skip-project-path"
	SkipProjectWikiPath = "skip-project-wiki-path"
	AutoSkipExistFolder = "auto-skip-exist-folder"
	AllowFailure        = "allow-failure"
	EnvName             = "name"
	EnvExternalUrl      = "external_url"
	EnvTier             = "tier"
)
