package constant

// 此处变量是议题专用变量，如果有重名变量（多个接口使用的变量，将移至 common.go 中）
const (
	AssigneeId        = "assignee-id"
	AssigneeUsername  = "assignee-username"
	AuthorId          = "author-id"
	AuthorUsername    = "author-username"
	Confidential      = "confidential"
	CreatedAfter      = "created-after"
	CreatedBefore     = "created-before"
	DueDate           = "due-date"
	EpicId            = "epic-id"
	HealthStatus      = "health-status"
	Iids              = "iids"
	In                = "in"
	IssueType         = "issue-type"
	IterationId       = "iteration-id"
	IterationTitle    = "iteration-title"
	Labels            = "labels"
	Milestone         = "milestone"
	MilestoneId       = "milestone-id"
	MyReactionEmoji   = "my-reaction-emoji"
	NonArchived       = "non-archived"
	Not               = "not"
	OrderBy           = "order-by"
	Scope             = "scope"
	Search            = "search"
	State             = "state"
	UpdatedAfter      = "updated-after"
	UpdatedBefore     = "updated-before"
	Weight            = "weight"
	WithLabelsDetails = "with-labels-details"
)
